name: Build Snisago Music (Windows)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Скачивание исходного кода
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Установка зависимостей (npm install)
        run: npm install

      - name: Компиляция и публикация релиза на GitHub
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Сохранение готового установщика и latest.yml в артефакты
        uses: actions/upload-artifact@v4
        with:
          name: Snisago-Music-Installer
          path: |
            dist/*.exe
            dist/latest.yml

      - name: Уведомление в Discord
        if: success()
        shell: bash
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Автоматически достаем версию из package.json (например, 1.1.8)
          APP_VERSION=$(node -p "require('./package.json').version")
          
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "🎉 ||@here|| Вышло новое обновление!",
            "embeds": [{
              "title": "Snisago Music обновлен до версии '"$APP_VERSION"'",
              "description": "Сборка завершена! Плеер сам скачает обновление в фоне. Также вы можете зайти в **Настройки ➔ Обновления плеера**, чтобы установить его прямо сейчас.",
              "color": 9133238,
              "footer": {
                "text": "Snisago Music Update System"
              }
            }]
          }' \
          $DISCORD_WEBHOOK
